'use client';
import { ChangeEvent, FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function Home() {
  const router=useRouter(); const [url,setUrl]=useState(''); const [status,setStatus]=useState('');
  async function assess(payload: object) { const res=await fetch('/api/assess',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}); const data=await res.json() as {error?:string;id?:string};if(!res.ok||!data.id){setStatus(data.error||'The assessment could not be created.');return;}router.push(`/r/${data.id}`); }
  async function submit(event: FormEvent) { event.preventDefault();setStatus('Reading listing…');await assess({url}); }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file=event.target.files?.[0];if(!file)return;setStatus('Reading Exposé…');try{const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/5.4.394/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let page=1;page<=pdf.numPages;page++){const content=await pdf.getPage(page).then(x=>x.getTextContent());text+=content.items.map(x=>('str' in x?x.str:'')).join(' ')+'\n';}if(text.trim().length<150){setStatus('This PDF appears to be scanned. Please upload a text-searchable Exposé.');return;}await assess({text,name:file.name});}catch{setStatus('The PDF could not be read. Try a text-searchable Exposé.');}}
  return <main className="landing"><nav><a className="logo" href="/">h <span>habitat</span></a><a href="#how">How it works</a></nav><section className="hero"><p className="eyebrow">GERMAN REAL ESTATE, EXPLAINED</p><h1>See the home.<br/><em>Not the sales pitch.</em></h1><p className="lead">A calm, buyer-first assessment of price, place, energy and financing—built for German property decisions.</p><form onSubmit={submit} className="intake"><label><span>↗</span><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Paste a property listing URL" type="url" required/></label><button>Assess property →</button></form><label style={{display:'inline-block',marginTop:12,cursor:'pointer',fontSize:12,color:'#587168'}}>Upload Exposé PDF <input onChange={upload} accept="application/pdf" type="file"/></label><p className={status && !status.includes('Reading') ? 'error' : 'hint'}>{status || '2 free assessments daily · We only use AI when source data is materially incomplete.'}</p></section><section id="how" className="steps"><div><b>01</b><h2>Import</h2><p>We validate a listing before doing any work.</p></div><div><b>02</b><h2>Extract</h2><p>Deterministic data extraction keeps results traceable.</p></div><div><b>03</b><h2>Decide</h2><p>Compare saved reports and share a focused view.</p></div></section></main>;
}
