import type { ReadinessItem } from './validate.ts';

const en = {
  nav: { buy: 'Buy', sell: 'Sell', review: 'Review a listing' },
  hub: {
    eyebrow: 'Homes for sale, reviewed',
    title: 'Find a home.',
    emphasis: 'Read it clearly.',
    lede: 'Recent flats and houses from private sellers, each with an independent review you can open for free.',
    cities: 'Choose a city',
    homes: (n: number) => `${n} ${n === 1 ? 'home' : 'homes'}`,
    from: 'from',
    sellTitle: 'Selling your own home?',
    sellText: 'Drop in photos and documents. We draft the listing, you polish it, and you share one link everywhere. Free while in beta.',
    sellCta: 'List your home',
    newest: 'Newest everywhere',
    seeAll: 'See all',
    elsewhere: 'Elsewhere in Germany',
  },
  search: {
    title: (city: string) => `Homes for sale in ${city}`,
    results: (n: number) => `${n} ${n === 1 ? 'home' : 'homes'}`,
    all: 'All',
    flat: 'Flats',
    house: 'Houses',
    land: 'Plots',
    maxPrice: 'Max price',
    any: 'Any',
    minSize: 'Min size',
    rooms: 'Rooms',
    district: 'Area',
    allAreas: 'All areas',
    sort: 'Sort',
    sortNewest: 'Newest',
    sortPriceLow: 'Price, low to high',
    sortPriceHigh: 'Price, high to low',
    sortPerSqm: 'Price per m²',
    sortScore: 'Review score',
    list: 'List',
    map: 'Map',
    reset: 'Clear filters',
    empty: 'No homes match these filters.',
    emptyCity: 'No homes listed here yet.',
    areaActive: 'Only homes inside the map area',
    searchArea: 'Search this area',
    showAll: 'Show all',
  },
  card: {
    perSqm: '/m²',
    review: 'Review',
    reviewScore: 'Review score',
    noScore: 'Review',
    compare: 'Compare',
    comparing: 'Selected',
    share: 'Share',
    copied: 'Link copied',
    via: 'via',
    privateSeller: 'Private seller',
    photo: (index: number, total: number) => `Photo ${index} of ${total}`,
    previous: 'Previous photo',
    next: 'Next photo',
    noPhoto: 'No photo yet',
  },
  compare: {
    tray: (n: number): string => n === 1 ? 'Select one more home to compare' : 'Two homes selected',
    go: 'Compare side by side',
    clear: 'Clear',
    working: 'Opening…',
    failed: 'The comparison could not be created. Try again.',
  },
  listing: {
    price: 'Price',
    perSqm: 'Price per m²',
    area: 'Living space',
    plot: 'Plot',
    rooms: 'Rooms',
    floor: 'Floor',
    year: 'Built',
    condition: 'Condition',
    energy: 'Energy class',
    heating: 'Heating',
    housegeld: 'Hausgeld',
    perMonth: '/ month',
    available: 'Available',
    features: 'Features',
    about: 'About this home',
    location: 'Location',
    approximate: 'Approximate location. The seller shares the exact address on request.',
    contact: 'Contact the seller',
    email: 'Email',
    call: 'Call',
    emailSubject: (title: string) => `Your listing on Review a House: ${title}`,
    emailBody: (url: string) => `Hello,\n\nI saw your listing on Review a House (${url}) and would like to know more.\n\n`,
    viaPortal: (name: string) => `Contact on ${name}`,
    importedNote: (name: string) => `Listed by a private seller on ${name}. Contact and viewing requests go through that page.`,
    reviewTitle: 'Our review',
    reviewText: 'Price check, location, energy, running costs and the questions to ask before an offer.',
    reviewOpen: 'Open the full review',
    reviewFree: 'Free',
    reviewPending: 'The review appears once the listing is live.',
    share: 'Share',
    copyLink: 'Copy link',
    copied: 'Copied',
    gallery: 'Show all photos',
    unavailable: 'This listing is no longer available.',
    backToCity: (city: string) => `More homes in ${city}`,
    listedOn: (date: string) => `Listed ${date}`,
    report: 'Report this listing',
    out: '/10',
  },
  sell: {
    eyebrow: 'Sell privately · free in beta',
    title: 'Your home,',
    emphasis: 'listed beautifully.',
    lede: 'Add photos and any documents you have. We draft a clean listing from them. You edit it on the page, publish, and share one link.',
    stepType: 'What are you selling?',
    flat: 'Flat',
    house: 'House',
    land: 'Plot',
    stepFiles: 'Add photos and documents',
    drop: 'Drop photos and PDFs here',
    dropOr: 'or',
    browse: 'choose files',
    dropHint: 'Photos as JPEG, PNG or WebP. Documents as PDF: Exposé, energy certificate, floor plan.',
    paste: 'Or paste a description',
    pastePlaceholder: 'Price, size, rooms, address, anything you would tell a buyer…',
    create: 'Create my draft',
    creating: 'Creating your draft…',
    readingPdf: (name: string) => `Reading ${name}`,
    resizing: (done: number, total: number) => `Preparing photos ${done} of ${total}`,
    uploading: (done: number, total: number) => `Uploading photos ${done} of ${total}`,
    drafting: 'Writing your draft',
    needSomething: 'Add at least one photo, a PDF or a short description.',
    photos: (n: number) => `${n} ${n === 1 ? 'photo' : 'photos'}`,
    documents: (n: number) => `${n} ${n === 1 ? 'document' : 'documents'}`,
    remove: 'Remove',
    private: 'Your draft stays private until you publish it.',
    how1: 'Drop files', how1Text: 'Photos, Exposé, energy certificate.',
    how2: 'Edit on the page', how2Text: 'Click any text or number to change it.',
    how3: 'Publish and share', how3Text: 'One link for WhatsApp, email and portals.',
    pdfFailed: (name: string) => `${name} could not be read. Its text was skipped.`,
    photoFailed: (name: string) => `${name} could not be used as a photo.`,
  },
  editor: {
    draft: 'Draft',
    live: 'Live',
    saving: 'Saving…',
    saved: 'Saved',
    saveFailed: 'Not saved. Check your connection.',
    preview: 'Preview',
    edit: 'Edit',
    publish: 'Publish',
    update: 'Live · up to date',
    unpublish: 'Take offline',
    ready: (done: number, total: number) => `${done} of ${total} ready`,
    missing: {
      title: 'Headline',
      price: 'Price',
      size: 'Size',
      location: 'Address',
      photos: 'At least one photo',
      contact: 'Contact details',
      consent: 'Confirmation',
    } satisfies Record<ReadinessItem, string>,
    clickToEdit: 'Click to edit',
    addTitle: 'Add a headline',
    addDescription: 'Describe the home in your own words: light, neighbours, what you will miss.',
    autoText: 'Written from your facts. Click to write your own.',
    resetText: 'Use generated text',
    addPhotos: 'Add photos',
    cover: 'Cover',
    makeCover: 'Make cover',
    deletePhoto: 'Delete photo',
    dragHint: 'Drag to reorder. The first photo is the cover.',
    street: 'Street and number',
    postalCode: 'Postcode',
    city: 'City',
    district: 'Area',
    showExact: 'Show the exact address',
    showExactHint: 'Off: buyers see the street and area, and the map pin is approximate.',
    notSet: 'Add',
    yes: 'Yes',
    privateLink: 'Your private edit link',
    privateLinkHint: 'Anyone with this link can edit the listing. Keep it to yourself.',
    copy: 'Copy',
    copied: 'Copied',
    publishTitle: 'Ready to publish',
    contactTitle: 'How buyers reach you',
    name: 'Your name',
    email: 'Email',
    phone: 'Phone (optional)',
    showEmail: 'Show my email',
    showPhone: 'Show my phone number',
    contactHint: 'We never sell your details. Your email stays with us even when hidden, so we can reach you about the listing.',
    consent: 'I own this property or may sell it, and I took these photos or may use them.',
    publishFree: 'Publish for free',
    publishing: 'Publishing…',
    stillMissing: 'Still missing:',
    liveTitle: 'Your listing is live',
    liveText: 'Share the link anywhere. Changes you make here appear on it straight away.',
    view: 'View listing',
    promote: 'Promote this listing',
    promoteText: 'Featured placement in the city list. Coming soon, free during beta.',
    soon: 'Soon',
    close: 'Close',
    notFound: 'This draft could not be opened. Use the private edit link you saved when you created it.',
    typeLabel: 'Type',
    features: 'Features',
    deleted: 'This listing was removed.',
  },
  share: {
    title: 'Share this listing',
    whatsapp: 'WhatsApp',
    telegram: 'Telegram',
    email: 'Email',
    facebook: 'Facebook',
    x: 'X',
    linkedin: 'LinkedIn',
    more: 'More…',
    text: (title: string) => `${title} — on Review a House`,
  },
  roadmap: {
    title: 'Where Review a House is going',
    lede: 'One place for the whole purchase: finding a home, judging it, buying it and making it yours.',
    now: 'Now',
    next: 'Next',
    later: 'Later',
  },
};

export type MarketCopy = typeof en;

const de: MarketCopy = {
  nav: { buy: 'Kaufen', sell: 'Verkaufen', review: 'Angebot prüfen' },
  hub: {
    eyebrow: 'Immobilien zum Kauf, geprüft',
    title: 'Finde ein Zuhause.',
    emphasis: 'Klar beschrieben.',
    lede: 'Aktuelle Wohnungen und Häuser von privaten Verkäufern, jeweils mit einer unabhängigen Prüfung, die du kostenlos öffnen kannst.',
    cities: 'Stadt wählen',
    homes: (n: number) => `${n} ${n === 1 ? 'Angebot' : 'Angebote'}`,
    from: 'ab',
    sellTitle: 'Du verkaufst selbst?',
    sellText: 'Fotos und Unterlagen hochladen. Wir entwerfen das Inserat, du verfeinerst es und teilst einen Link überall. Kostenlos in der Beta.',
    sellCta: 'Inserat erstellen',
    newest: 'Neu überall',
    seeAll: 'Alle ansehen',
    elsewhere: 'Weitere Orte in Deutschland',
  },
  search: {
    title: (city: string) => `Immobilien kaufen in ${city}`,
    results: (n: number) => `${n} ${n === 1 ? 'Angebot' : 'Angebote'}`,
    all: 'Alle',
    flat: 'Wohnungen',
    house: 'Häuser',
    land: 'Grundstücke',
    maxPrice: 'Preis bis',
    any: 'Egal',
    minSize: 'Fläche ab',
    rooms: 'Zimmer',
    district: 'Gegend',
    allAreas: 'Alle Gegenden',
    sort: 'Sortierung',
    sortNewest: 'Neueste',
    sortPriceLow: 'Preis aufsteigend',
    sortPriceHigh: 'Preis absteigend',
    sortPerSqm: 'Preis pro m²',
    sortScore: 'Bewertung',
    list: 'Liste',
    map: 'Karte',
    reset: 'Filter zurücksetzen',
    empty: 'Keine Angebote passen zu diesen Filtern.',
    emptyCity: 'Hier gibt es noch keine Angebote.',
    areaActive: 'Nur Angebote im Kartenausschnitt',
    searchArea: 'In diesem Bereich suchen',
    showAll: 'Alle zeigen',
  },
  card: {
    perSqm: '/m²',
    review: 'Prüfung',
    reviewScore: 'Bewertung',
    noScore: 'Prüfung',
    compare: 'Vergleichen',
    comparing: 'Ausgewählt',
    share: 'Teilen',
    copied: 'Link kopiert',
    via: 'über',
    privateSeller: 'Privatverkauf',
    photo: (index: number, total: number) => `Foto ${index} von ${total}`,
    previous: 'Vorheriges Foto',
    next: 'Nächstes Foto',
    noPhoto: 'Noch kein Foto',
  },
  compare: {
    tray: (n: number) => n === 1 ? 'Noch ein Angebot zum Vergleichen wählen' : 'Zwei Angebote ausgewählt',
    go: 'Nebeneinander vergleichen',
    clear: 'Leeren',
    working: 'Wird geöffnet…',
    failed: 'Der Vergleich konnte nicht erstellt werden. Bitte erneut versuchen.',
  },
  listing: {
    price: 'Kaufpreis',
    perSqm: 'Preis pro m²',
    area: 'Wohnfläche',
    plot: 'Grundstück',
    rooms: 'Zimmer',
    floor: 'Etage',
    year: 'Baujahr',
    condition: 'Zustand',
    energy: 'Energieklasse',
    heating: 'Heizung',
    housegeld: 'Hausgeld',
    perMonth: '/ Monat',
    available: 'Verfügbar',
    features: 'Ausstattung',
    about: 'Über dieses Zuhause',
    location: 'Lage',
    approximate: 'Ungefähre Lage. Die genaue Adresse nennt der Verkäufer auf Anfrage.',
    contact: 'Verkäufer kontaktieren',
    email: 'E-Mail',
    call: 'Anrufen',
    emailSubject: (title: string) => `Ihr Inserat auf Review a House: ${title}`,
    emailBody: (url: string) => `Guten Tag,\n\nich habe Ihr Inserat auf Review a House gesehen (${url}) und interessiere mich dafür.\n\n`,
    viaPortal: (name: string) => `Kontakt über ${name}`,
    importedNote: (name: string) => `Von einem privaten Verkäufer auf ${name} inseriert. Kontakt und Besichtigung laufen über diese Seite.`,
    reviewTitle: 'Unsere Prüfung',
    reviewText: 'Preisvergleich, Lage, Energie, laufende Kosten und die Fragen vor einem Angebot.',
    reviewOpen: 'Ganze Prüfung öffnen',
    reviewFree: 'Kostenlos',
    reviewPending: 'Die Prüfung erscheint, sobald das Inserat online ist.',
    share: 'Teilen',
    copyLink: 'Link kopieren',
    copied: 'Kopiert',
    gallery: 'Alle Fotos zeigen',
    unavailable: 'Dieses Angebot ist nicht mehr verfügbar.',
    backToCity: (city: string) => `Weitere Angebote in ${city}`,
    listedOn: (date: string) => `Inseriert am ${date}`,
    report: 'Inserat melden',
    out: '/10',
  },
  sell: {
    eyebrow: 'Privat verkaufen · kostenlos in der Beta',
    title: 'Dein Zuhause,',
    emphasis: 'schön inseriert.',
    lede: 'Füge Fotos und vorhandene Unterlagen hinzu. Wir entwerfen daraus ein klares Inserat. Du bearbeitest es direkt auf der Seite, veröffentlichst und teilst einen Link.',
    stepType: 'Was verkaufst du?',
    flat: 'Wohnung',
    house: 'Haus',
    land: 'Grundstück',
    stepFiles: 'Fotos und Unterlagen hinzufügen',
    drop: 'Fotos und PDFs hier ablegen',
    dropOr: 'oder',
    browse: 'Dateien wählen',
    dropHint: 'Fotos als JPEG, PNG oder WebP. Unterlagen als PDF: Exposé, Energieausweis, Grundriss.',
    paste: 'Oder eine Beschreibung einfügen',
    pastePlaceholder: 'Preis, Fläche, Zimmer, Adresse, alles, was du Käufern erzählen würdest…',
    create: 'Entwurf erstellen',
    creating: 'Entwurf wird erstellt…',
    readingPdf: (name: string) => `${name} wird gelesen`,
    resizing: (done: number, total: number) => `Fotos werden vorbereitet: ${done} von ${total}`,
    uploading: (done: number, total: number) => `Fotos werden hochgeladen: ${done} von ${total}`,
    drafting: 'Entwurf wird geschrieben',
    needSomething: 'Füge mindestens ein Foto, ein PDF oder eine kurze Beschreibung hinzu.',
    photos: (n: number) => `${n} ${n === 1 ? 'Foto' : 'Fotos'}`,
    documents: (n: number) => `${n} ${n === 1 ? 'Dokument' : 'Dokumente'}`,
    remove: 'Entfernen',
    private: 'Dein Entwurf bleibt privat, bis du ihn veröffentlichst.',
    how1: 'Dateien ablegen', how1Text: 'Fotos, Exposé, Energieausweis.',
    how2: 'Auf der Seite bearbeiten', how2Text: 'Text oder Zahl anklicken und ändern.',
    how3: 'Veröffentlichen und teilen', how3Text: 'Ein Link für WhatsApp, E-Mail und Portale.',
    pdfFailed: (name: string) => `${name} konnte nicht gelesen werden. Der Text wurde übersprungen.`,
    photoFailed: (name: string) => `${name} konnte nicht als Foto verwendet werden.`,
  },
  editor: {
    draft: 'Entwurf',
    live: 'Online',
    saving: 'Wird gespeichert…',
    saved: 'Gespeichert',
    saveFailed: 'Nicht gespeichert. Prüfe deine Verbindung.',
    preview: 'Vorschau',
    edit: 'Bearbeiten',
    publish: 'Veröffentlichen',
    update: 'Online · aktuell',
    unpublish: 'Offline nehmen',
    ready: (done: number, total: number) => `${done} von ${total} erledigt`,
    missing: {
      title: 'Überschrift',
      price: 'Preis',
      size: 'Fläche',
      location: 'Adresse',
      photos: 'Mindestens ein Foto',
      contact: 'Kontaktdaten',
      consent: 'Bestätigung',
    },
    clickToEdit: 'Zum Bearbeiten klicken',
    addTitle: 'Überschrift hinzufügen',
    addDescription: 'Beschreibe das Zuhause in eigenen Worten: Licht, Nachbarschaft, was du vermissen wirst.',
    autoText: 'Aus deinen Angaben geschrieben. Klicke, um eigenen Text zu schreiben.',
    resetText: 'Erzeugten Text verwenden',
    addPhotos: 'Fotos hinzufügen',
    cover: 'Titelbild',
    makeCover: 'Als Titelbild',
    deletePhoto: 'Foto löschen',
    dragHint: 'Zum Sortieren ziehen. Das erste Foto ist das Titelbild.',
    street: 'Straße und Hausnummer',
    postalCode: 'PLZ',
    city: 'Ort',
    district: 'Gegend',
    showExact: 'Genaue Adresse zeigen',
    showExactHint: 'Aus: Käufer sehen Straße und Gegend, der Kartenpunkt ist ungefähr.',
    notSet: 'Hinzufügen',
    yes: 'Ja',
    privateLink: 'Dein privater Bearbeitungslink',
    privateLinkHint: 'Wer diesen Link hat, kann das Inserat bearbeiten. Behalte ihn für dich.',
    copy: 'Kopieren',
    copied: 'Kopiert',
    publishTitle: 'Bereit zum Veröffentlichen',
    contactTitle: 'So erreichen dich Käufer',
    name: 'Dein Name',
    email: 'E-Mail',
    phone: 'Telefon (optional)',
    showEmail: 'E-Mail anzeigen',
    showPhone: 'Telefonnummer anzeigen',
    contactHint: 'Wir verkaufen deine Daten nie. Deine E-Mail bleibt bei uns, auch wenn sie verborgen ist, damit wir dich zum Inserat erreichen.',
    consent: 'Mir gehört diese Immobilie oder ich darf sie verkaufen, und ich habe die Fotos gemacht oder darf sie nutzen.',
    publishFree: 'Kostenlos veröffentlichen',
    publishing: 'Wird veröffentlicht…',
    stillMissing: 'Es fehlt noch:',
    liveTitle: 'Dein Inserat ist online',
    liveText: 'Teile den Link überall. Änderungen hier erscheinen sofort im Inserat.',
    view: 'Inserat ansehen',
    promote: 'Inserat hervorheben',
    promoteText: 'Hervorgehobene Platzierung in der Stadtliste. Bald verfügbar, in der Beta kostenlos.',
    soon: 'Bald',
    close: 'Schließen',
    notFound: 'Dieser Entwurf lässt sich nicht öffnen. Nutze den privaten Bearbeitungslink, den du beim Erstellen gespeichert hast.',
    typeLabel: 'Art',
    features: 'Ausstattung',
    deleted: 'Dieses Inserat wurde entfernt.',
  },
  share: {
    title: 'Inserat teilen',
    whatsapp: 'WhatsApp',
    telegram: 'Telegram',
    email: 'E-Mail',
    facebook: 'Facebook',
    x: 'X',
    linkedin: 'LinkedIn',
    more: 'Mehr…',
    text: (title: string) => `${title} — auf Review a House`,
  },
  roadmap: {
    title: 'Wohin sich Review a House entwickelt',
    lede: 'Ein Ort für den ganzen Kauf: Zuhause finden, einschätzen, kaufen und zu deinem machen.',
    now: 'Jetzt',
    next: 'Als Nächstes',
    later: 'Später',
  },
};

export const marketCopy = { en, de } as const;
