import type { Locale } from './i18n.ts';

/** User-facing provenance and feedback copy. British spelling in English. */
export const factSourceCopy = {
  en: {
    sourceFor: (label: string) => `Source for ${label}`,
    fromListing: 'From the listing:',
    noQuote: 'From the listing (no direct quote found)',
    calculated: (formula: string) => `Calculated: ${formula}`,
    estimate: (basis: string) => `Estimate: ${basis}`,
    official: (source: string) => `Official data: ${source}`,
    notStated: 'Not stated in the listing.',
    wrong: 'This is wrong',
    correctValue: 'Correct value',
    comment: 'Comment',
    optional: 'optional',
    send: 'Send',
    sending: 'Sending…',
    thanks: 'Thanks. We use this to fix extraction errors.',
    viewEvidence: 'View source evidence',
    evidenceNote: 'Excerpts from the source. Seller statements have not been independently verified.',
    sources: 'Sources',
    close: 'Close source',
    buyerCostsUnstated: 'Buyer costs are not stated in the listing',
    grossYieldFormula: 'Annual cold rent ÷ asking price',
    priceCheckUnsourced: 'No official price reference applies to this report.',
    fmhSource: 'FMH mortgage-rate index',
    sendFailed: 'Could not send the report. Please try again.',
    unavailable: 'Reporting a wrong value is not available yet. Please try again later.',
    tooMany: 'Too many reports, please try again later.',
    notFound: 'This report could not be found.',
    badField: 'Choose a fact from this report.',
    suggestedTooLong: 'The correct value can be up to 80 characters.',
    commentTooLong: 'The comment can be up to 300 characters.',
    reportedTooLong: 'The reported value is too long.',
    invalid: 'Check the form and try again.',
    origin: 'Invalid request origin.',
  },
  de: {
    sourceFor: (label: string) => `Quelle für ${label}`,
    fromListing: 'Aus dem Angebot:',
    noQuote: 'Aus dem Angebot (kein direktes Zitat gefunden)',
    calculated: (formula: string) => `Berechnet: ${formula}`,
    estimate: (basis: string) => `Schätzung: ${basis}`,
    official: (source: string) => `Amtliche Daten: ${source}`,
    notStated: 'Im Angebot nicht angegeben.',
    wrong: 'Das stimmt nicht',
    correctValue: 'Richtiger Wert',
    comment: 'Kommentar',
    optional: 'optional',
    send: 'Senden',
    sending: 'Wird gesendet…',
    thanks: 'Danke. Damit verbessern wir die Auslese.',
    viewEvidence: 'Belege aus dem Angebot ansehen',
    evidenceNote: 'Auszüge aus der Quelle. Angaben des Verkäufers sind nicht unabhängig bestätigt.',
    sources: 'Quellen',
    close: 'Quelle schließen',
    buyerCostsUnstated: 'Kaufnebenkosten sind im Angebot nicht angegeben',
    grossYieldFormula: 'Jahreskaltmiete ÷ Kaufpreis',
    priceCheckUnsourced: 'Für diesen Bericht gibt es keine amtliche Preisquelle.',
    fmhSource: 'FMH-Hypothekenzinsindex',
    sendFailed: 'Die Meldung konnte nicht gesendet werden. Bitte versuche es erneut.',
    unavailable: 'Eine Meldung zu einem falschen Wert ist noch nicht möglich. Bitte versuche es später erneut.',
    tooMany: 'Zu viele Meldungen, bitte später erneut versuchen.',
    notFound: 'Dieser Bericht wurde nicht gefunden.',
    badField: 'Bitte wähle eine Angabe aus diesem Bericht.',
    suggestedTooLong: 'Der richtige Wert darf höchstens 80 Zeichen lang sein.',
    commentTooLong: 'Der Kommentar darf höchstens 300 Zeichen lang sein.',
    reportedTooLong: 'Der gemeldete Wert ist zu lang.',
    invalid: 'Bitte prüfe das Formular und versuche es erneut.',
    origin: 'Ungültige Anfrage.',
  },
} as const;

export type FactSourceCopy = (typeof factSourceCopy)[Locale];
