export type Facts = {
  price: number;
  area: number;
  usableArea?: number;
  rooms: string;
  year: string;
  floor: string;
  energy: string;
  heating: string;
  energySource?: string;
  energyDemand?: number;
  energyCertificate?: string;
  totalCost: number;
  buyerCosts?: number;
  brokerFee?: number;
  housegeld?: number;
  tenancy?: string;
  advertisedYield?: number;
  condition?: string;
  features?: string[];
  postalCode?: string;
  city?: string;
  district?: string;
};

export type Report = {
  id: string;
  title: string;
  address: string;
  location?: string;
  propertyType: 'flat' | 'house';
  source: string;
  createdAt: string;
  facts: Facts;
  score: number;
  scoreTitle?: string;
  summary: string;
  considerations: string[];
  offerQuestions?: string[];
  sunOrientation: string;
  daylight?: string;
  qualityWarnings?: string[];
  aiEnriched: boolean;
};
export type Comparison = { id: string; reportIds: [string, string]; createdAt: string };
